### ISSUE TITLE
Timestamp on each chat line

### ISSUE THREAD

**Issue by ThePerry-2015** [ebiggz/MixrElixr#14]
Add option for putting a timestamp on each chat line.

**Comment by Firebottle** [comment]
Notes:
- started new branch with the base for this.

Problems:
- The selector for timestamps can change from c60 to c58, etc... based on chat. So we need to put all the styles for this into our stylesheet and not rely on mixers.
- in the branch right now two timestamps are added for each message. One where it's supposed to go above the message, and the other at the very bottom of chat. Not sure why this is happening.

**Comment by ebiggz** [comment]
I made some tweaks based on FB's great work, and I think the lingering issues are resolved.
