### ISSUE TITLE
changing tabs breaks video hover effect

### ISSUE THREAD

**Issue by Firebottle** [ebiggz/MixrElixr#18]
You'll notice on the who's online page that if you mouse over a stream it replaces the static image with a short video of whats going on.

For some reason if you go to the options page, then back to the who's online page, this hover effects breaks.

**Comment by ebiggz** [comment]
I fixed this by changing the `v-show` directive on the video element to `v-if`. Similarly to Angular, `v-show` just add (or removes) 'display:none' to the element style so the element still remains in the dom. Whereas `v-if` completely removes or adds the element to the dom. Something weird was happening causing the videos to no auto play anymore if we changed tabs so using `v-if` instead means the video element is refreshed in the dom every time we hover over the element.This also means we dont have hidden video elements playing for every online friend, only for the one we are currently hovering over.
