### ISSUE TITLE
[Bug] Not showing streams without a game set

### ISSUE THREAD

**Issue by MAPReiff** [ebiggz/MixrElixr#33]
When only 1 streamer I'm following is live, it will have a badge on the plugin with 1, but not show it in the plugin's popup.

<img width="1680" alt="saejkl" src="https://user-images.githubusercontent.com/7242589/32546429-145400ba-c44d-11e7-811c-9c400ae6c119.png">

**Comment by ThePerry-2015** [comment]
That's weird, on my end it works just fine.
![unknown](https://user-images.githubusercontent.com/25306770/32546909-d82da62a-c480-11e7-93c3-b3ab98d3ca85.png)
Which version of MixrElixr are you using? Should be able to see the version # on chrome://extensions

**Comment by MAPReiff** [comment]
Version 1.2, chrome version 62.0.3202.89 on MacOS.

**Comment by ThePerry-2015** [comment]
I just reinstalled my extension from the Webstore as I was using the source code directly in Chrome to see if that made any change, but it still shows me the one stream that I'm following just fine. Might have to wait and see if there are anyone else with the same issue as I can't see why it should be showing up differently for you, even if you are on Mac OS.
I was on an older Chrome for some reason, but I upgraded to the same version as you and it still shows up like it should.

Plugin: 1.2
Chrome: Version 62.0.3202.89 (Official Build) (64-bit)
Windows 10 Pro Insider Preview
Build: 17025_rs_prerelease.171020-1626

**Comment by MAPReiff** [comment]
I highly doubt it, but perhaps its the MacOS version of chrome which has the issue. I'll try it on my Windows rig when I get back home and see if what happens.

**Comment by ebiggz** [comment]
I have a feeling this is probably related to a bug we know about (but haven’t made a issue for, I need to do that still) where any streamer that doesn’t have a game set won’t show up in the list. It’s possible that the one streamer online didn’t have a game set and thus, wasn’t showing up.

**Comment by ThePerry-2015** [comment]
You are completely right @ebiggz, I didn't think of that one when I saw this one. But if you check the screenshot in the first post you see that it's Monstercat and they don't have a game set as you only see their title. So that is the issue here.

**Comment by ebiggz** [comment]
I totally missed the screenshot. Yup, that’s got to be it.

**Comment by MAPReiff** [comment]
If its an issue with no game being set, is it that its looking for a game string from the api to place on the stream preview in the plugin, not finding one, and thus not posting the stream? I'm not sure if this would apply to how you guys do it, but why not just have something like (game = null){var game = "No Game"} to make sure game-less are given a string, and thus work.

**Comment by Firebottle** [comment]
Yeah, thats exactly what needs to happen. You can blame me for that one. Didn't even think about streams not having titles or games set. We can get it fixed soon.

**Comment by ebiggz** [comment]
@MAPReiff Yup we know how to get it to work, it was just an oversight. It'll be in the next release :)
